name: pg_manager_app
description: "PG Management App for owners and tenants to manage PG operations efficiently."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  provider: ^6.1.1
  
  # Navigation
  go_router: ^12.1.2
  
  # Animations
  flutter_animate: ^4.2.0
  
  # Backend & Database
  supabase_flutter: ^2.5.0
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  
  # HTTP & API
  dio: ^5.4.3
  
  # UI Components
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.5.1
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  url_launcher: ^6.2.5
  
  # Charts (for analytics)
  fl_chart: ^0.69.0
  
  # File handling
  file_picker: ^8.0.0+1
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  # Add assets
  assets:
    - assets/images/
    - assets/icons/
    
  # Google Fonts will be used instead of local font files
  # The google_fonts package is already in dependencies
  # fonts section has been removed since we're using google_fonts package
